### ISSUE TITLE
Support for Twig extensions?

### ISSUE THREAD

**Issue by kieranajp** [slimphp/Slim-Views#10]
Maybe I'm missing something, but I don't see a way in the docs to do `$twig->addExtension()`

After upgrading a project to slim-views from extras, I'm not able to use Twig's [dump](http://twig.sensiolabs.org/doc/functions/dump.html) function because of this

Is this functionality in the pipeline, or is it already there and I just need more coffee?

**Comment by kieranajp** [comment]
So while I found a way to add extensions manually, is there no way of automating this at all?

**Comment by silentworks** [comment]
This is now the parserExtension property, take a look at it here https://github.com/codeguy/Slim-Views#twig-1.

``` php
$view->parserExtensions = array(
    new Twig_Extension_Debug(),
);
```

**Comment by kieranajp** [comment]
Ah excellent, thank you!
