### ISSUE TITLE
Multiple template dirs

### ISSUE THREAD

**Issue by tuimz** [slimphp/Slim-Views#13]
Is it not possible to have multiple template directories?

```
$view->setTemplatesDirectory($dir);
```

seems to only accept one directory, as does the config. The $twigTemplateDirs will be deprecated it says, so I am not using that :)

**Comment by silentworks** [comment]
For now use $twigTemplateDirs, in the next major release you will be able to pass multiple directories. Currently the template directory is set in the Slim class and this will be moved to the views class instead in Slim 3.0.

**Comment by tuimz** [comment]
Awesome thanks!
