### ISSUE TITLE
Strict standards error

### ISSUE THREAD

**Issue by kennethrapp** [slimphp/Slim-Views#17]
I'm getting the following exception:

Strict Standards: Declaration of Slim\Views\Twig::render() should be compatible with that of Slim\View::render() 

I cleared it up by adding $data=null as a parameter to Slim\Views\Twig::render() even though the extra argument doesn't seem to be useful.

**Comment by silentworks** [comment]
There is a fix on the develop branch for this, I will be releasing a 0.1.1 release later on this evening.

**Comment by silentworks** [comment]
Fixed.
