### ISSUE TITLE
Twig dump function

### ISSUE THREAD

**Issue by dgee2** [slimphp/Slim-Views#32]
Hi I'm trying to use the dump function in a twig template but I get a "The function "dump" does not exist" error. I have the following parser options:

'charset' => 'utf-8',
'auto_reload' => true,
'strict_variables' => false,
'autoescape' => true,
'debug'=>true

Any suggestions would be greatfully recieved.

**Comment by tassoevan** [comment]
Did you activate debug mode in parser options?

``` php
<?php
$view->parserOptions['debug'] = true;
```

**Comment by dgee2** [comment]
Here is the code that I'm using to set up Twig. (`$this->slim` holds the slim application)

``` php
$this->slim->view(new \Slim\Views\Twig());
        $this->slim->view->parserOptions = array(
            'charset' => 'utf-8',
            'auto_reload' => true,
            'strict_variables' => false,
            'autoescape' => true,
            'debug'=>true
        );
        $this->slim->view->parserExtensions = array(new \Slim\Views\TwigExtension());
```

So in response to your question yes although is the ordering important?

**Comment by tassoevan** [comment]
Ok, and what about the Twig version? _I doubt it's the problem_, but must be greater than or equal to 1.5.

**Comment by dgee2** [comment]
Composer output below:

```
installed:
  dgee2/slim-plus    0.0.1              An extended version of the slim fram...
  lichtner/fluentpdo dev-master 936bb5f FluentPDO is small PHP library for r...
  slim/slim          2.4.3              Slim Framework, a PHP micro framework
  slim/views         0.1.2              Smarty and Twig View Parser package ...
  twig/twig          v1.16.0            Twig, the flexible, fast, and secure...
```

**Comment by silentworks** [comment]
You need to add the Debug extension.

``` php
$this->slim->view->parserExtensions = array(
    new \Twig_Extension_Debug(),
    new \Slim\Views\TwigExtension()
);
```
