### ISSUE TITLE
Add smarty & twig to the example composer.json

### ISSUE THREAD

**Issue by metalmatze** [slimphp/Slim-Views#5]
Isn't it that you have to require smarty or twig to use them?
This should be added to the example composer.json in the readme.

**Comment by nsierram** [comment]
Agree. I just get this working by adding twig (in my case) to the composer.json file.
Otherwise, fatal errors!

**Comment by silentworks** [comment]
Ah sorry for that, this is an oversight on my behalf, will fix it soon.

**Comment by silentworks** [comment]
Added these as suggests, I didn't want to include both as Smarty repo requires the use of SVN and not all user would want to have both Smarty and Twig codebase at the same time. So its down to the user to install which they need.
