### ISSUE TITLE
current Slim-Views master requires a too low Slim-Version in composer.json

### ISSUE THREAD

**Issue by qyanu** [slimphp/Slim-Views#6]
Slim-Views calls "$this->all()" method in Twig.php:88, which is not provided in Slim only since 2.3.0

git diff:
diff --git a/composer.json b/composer.json
index ad88722..14b8286 100644
--- a/composer.json
+++ b/composer.json
@@ -18,7 +18,7 @@
         }
     ],
     "require": {
-        "slim/slim": ">=2.2.0",
-        "slim/slim": ">=2.3.0",
       "php": ">=5.3.0"
   },
   "autoload": {

**Comment by silentworks** [comment]
Fixed.
