### ISSUE TITLE
Other templating

### ISSUE THREAD

**Issue by fmitchell** [slimphp/Slim-Views#8]
I'm a little confused. If I want to use Mustache, would you accept a pull request to this repo or should I use the deprecated repo or am I supposed to use this, fork, write my own and not contribute back?

I saw that you wanted it to be smaller, but wasn't clear if others wanted to use a different templating engine.

Thanks again!!

**Comment by silentworks** [comment]
We won't be officially be supporting or maintaining a Mustache View, if you want to create a repo with one and maintain it, feel free to do so, provide a link back to this issue once done as we are working on a extras website that will aggregate extras from Packagist with the slimphp keyword.

**Comment by eridal** [comment]
Hey @fmitchell ,
I'm looking to use Mustache as well. I'm currently using `mustache/mustache`, but there's no integration with Slim out-of-the-box.
Have you solved this?

**Comment by fmitchell** [comment]
I didn't use Slim Views. I simply extended the mustache template and instantiated what I needed.

Setup: https://github.com/fmitchell/jotmap/blob/master/src/mustache.php
Example usage: https://github.com/fmitchell/jotmap/blob/master/templates/step1.php

**Comment by eridal** [comment]
so cool!! does it works with Slim's `$app->render('template.html', $vars);` ??

**Comment by fmitchell** [comment]
Yes. The second link has an example.
